apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:          # dev/local
    path: /mnt/data/minio
  persistentVolumeReclaimPolicy: Retain
